### ISSUE TITLE
memory leak in pngtoimage

### ISSUE THREAD

**Issue by bestshow** [uclouvain/openjpeg#1002]
On openjpeg lastest version.
A memory leak vulnerability was found in function pngtoimage in jp2/convertpng.c,which allow attackers to cause a denial of service via a crafted file.

```
./opj_compress -i $FILE -o OUT.j2k
=================================================================
==65357==ERROR: detected memory leaks

Direct leak of 520 byte(s) in 1 object(s) allocated from:
    #0 0x4e1bbd in calloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:74
    #1 0x5b1636 in pngtoimage /home/test/Downloads/openjpeg-master-afl/openjpeg-master/src/bin/jp2/convertpng.c:191:24
    #2 0x518c78 in main /home/test/Downloads/openjpeg-master-afl/openjpeg-master/src/bin/jp2/opj_compress.c:1890:21
    #3 0x7f74ecc7db34 in __libc_start_main /usr/src/debug/glibc-2.17-c758a686/csu/../csu/libc-start.c:274

Indirect leak of 12288 byte(s) in 64 object(s) allocated from:
    #0 0x4e1a06 in malloc /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0x5b1749 in pngtoimage /home/test/Downloads/openjpeg-master-afl/openjpeg-master/src/bin/jp2/convertpng.c:197:30
    #2 0x518c78 in main /home/test/Downloads/openjpeg-master-afl/openjpeg-master/src/bin/jp2/opj_compress.c:1890:21
    #3 0x7f74ecc7db34 in __libc_start_main /usr/src/debug/glibc-2.17-c758a686/csu/../csu/libc-start.c:274

12808 byte(s) leaked in 65 allocation(s).
```

testcase:https://github.com/bestshow/p0cs/blob/master/memory_leak_in_pngtoimage.png
Credit:ADLab of Venustech

**Comment by rouault** [comment]
I can't reproduce any leak on a -fsanitize=address build, nor with Valgrind

Here's the output I get
```
$ bin/opj_compress -i ../memory_leak_in_pngtoimage.png -o out.j2k

libpng warning: tRNS: CRC error
libpng error: Read Error
Unable to load png file
```

**Comment by kbabioch** [comment]
Same for me, cannot reproduce.

@bestshow: Which version of openJPEG were you using?
