### ISSUE TITLE
allocation failure in opj_aligned_alloc_n

### ISSUE THREAD

**Issue by bestshow** [uclouvain/openjpeg#1003]
On openjpeg lastest version.
An allocation failure vulnerability was found in function opj_aligned_alloc_n in openjp2/opj_malloc.c ,which allow attackers to cause a denial of service via a crafted file.

```
./opj_compress -i $FILE -o OUT.j2k
==65390==ERROR: AddressSanitizer failed to allocate 0x180004000 (6442467328) bytes of LargeMmapAllocator (error code: 12)
==65390==Process memory map follows:
    0x000000400000-0x0000005f8000    /home/test/Downloads/openjpeg-master-afl/openjpeg-master/build/bin/opj_compress
    0x0000007f8000-0x0000007f9000    /home/test/Downloads/openjpeg-master-afl/openjpeg-master/build/bin/opj_compress
    0x0000007f9000-0x000000803000    /home/test/Downloads/openjpeg-master-afl/openjpeg-master/build/bin/opj_compress
    0x000000803000-0x000001469000   
    0x00007fff7000-0x00008fff7000   
    0x00008fff7000-0x02008fff7000   
    0x02008fff7000-0x10007fff8000   
    0x600000000000-0x604000000000   
    0x604000000000-0x604000010000   
    0x604000010000-0x604e00000000   
    0x604e00000000-0x604e00010000   
    0x604e00010000-0x610000000000   
    0x610000000000-0x610000010000   
    0x610000010000-0x610e00000000   
    0x610e00000000-0x610e00010000   
    0x610e00010000-0x616000000000   
    0x616000000000-0x616000010000   
    0x616000010000-0x616e00000000   
    0x616e00000000-0x616e00010000   
    0x616e00010000-0x640000000000   
    0x640000000000-0x640000003000   
    0x7fc3137fd000-0x7fc373900000   
    0x7fc373a00000-0x7fc373b00000   
    0x7fc373c00000-0x7fc373d00000   
    0x7fc373e00000-0x7fc373f00000   
    0x7fc373f17000-0x7fc376269000   
    0x7fc376269000-0x7fc3762ac000    /usr/lib64/libjpeg.so.62.1.0
    0x7fc3762ac000-0x7fc3764ac000    /usr/lib64/libjpeg.so.62.1.0
    0x7fc3764ac000-0x7fc3764ad000    /usr/lib64/libjpeg.so.62.1.0
    0x7fc3764ad000-0x7fc3764ae000    /usr/lib64/libjpeg.so.62.1.0
    0x7fc3764ae000-0x7fc3764be000   
    0x7fc3764be000-0x7fc3764c7000    /usr/lib64/libjbig.so.2.0
    0x7fc3764c7000-0x7fc3766c6000    /usr/lib64/libjbig.so.2.0
    0x7fc3766c6000-0x7fc3766c7000    /usr/lib64/libjbig.so.2.0
    0x7fc3766c7000-0x7fc3766ca000    /usr/lib64/libjbig.so.2.0
    0x7fc3766ca000-0x7fc376880000    /usr/lib64/libc-2.17.so
    0x7fc376880000-0x7fc376a80000    /usr/lib64/libc-2.17.so
    0x7fc376a80000-0x7fc376a84000    /usr/lib64/libc-2.17.so
    0x7fc376a84000-0x7fc376a86000    /usr/lib64/libc-2.17.so
    0x7fc376a86000-0x7fc376a8b000   
    0x7fc376a8b000-0x7fc376aa0000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7fc376aa0000-0x7fc376c9f000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7fc376c9f000-0x7fc376ca0000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7fc376ca0000-0x7fc376ca1000    /usr/lib64/libgcc_s-4.8.5-20150702.so.1
    0x7fc376ca1000-0x7fc376ca3000    /usr/lib64/libdl-2.17.so
    0x7fc376ca3000-0x7fc376ea3000    /usr/lib64/libdl-2.17.so
    0x7fc376ea3000-0x7fc376ea4000    /usr/lib64/libdl-2.17.so
    0x7fc376ea4000-0x7fc376ea5000    /usr/lib64/libdl-2.17.so
    0x7fc376ea5000-0x7fc376ebc000    /usr/lib64/libpthread-2.17.so
    0x7fc376ebc000-0x7fc3770bb000    /usr/lib64/libpthread-2.17.so
    0x7fc3770bb000-0x7fc3770bc000    /usr/lib64/libpthread-2.17.so
    0x7fc3770bc000-0x7fc3770bd000    /usr/lib64/libpthread-2.17.so
    0x7fc3770bd000-0x7fc3770c1000   
    0x7fc3770c1000-0x7fc3770c8000    /usr/lib64/librt-2.17.so
    0x7fc3770c8000-0x7fc3772c7000    /usr/lib64/librt-2.17.so
    0x7fc3772c7000-0x7fc3772c8000    /usr/lib64/librt-2.17.so
    0x7fc3772c8000-0x7fc3772c9000    /usr/lib64/librt-2.17.so
    0x7fc3772c9000-0x7fc3773c9000    /usr/lib64/libm-2.17.so
    0x7fc3773c9000-0x7fc3775c9000    /usr/lib64/libm-2.17.so
    0x7fc3775c9000-0x7fc3775ca000    /usr/lib64/libm-2.17.so
    0x7fc3775ca000-0x7fc3775cb000    /usr/lib64/libm-2.17.so
    0x7fc3775cb000-0x7fc377620000    /usr/lib64/liblcms2.so.2.0.6
    0x7fc377620000-0x7fc37781f000    /usr/lib64/liblcms2.so.2.0.6
    0x7fc37781f000-0x7fc377820000    /usr/lib64/liblcms2.so.2.0.6
    0x7fc377820000-0x7fc377825000    /usr/lib64/liblcms2.so.2.0.6
    0x7fc377825000-0x7fc377894000    /usr/lib64/libtiff.so.5.2.0
    0x7fc377894000-0x7fc377a94000    /usr/lib64/libtiff.so.5.2.0
    0x7fc377a94000-0x7fc377a95000    /usr/lib64/libtiff.so.5.2.0
    0x7fc377a95000-0x7fc377a98000    /usr/lib64/libtiff.so.5.2.0
    0x7fc377a98000-0x7fc377a99000   
    0x7fc377a99000-0x7fc377aae000    /usr/lib64/libz.so.1.2.7
    0x7fc377aae000-0x7fc377cad000    /usr/lib64/libz.so.1.2.7
    0x7fc377cad000-0x7fc377cae000    /usr/lib64/libz.so.1.2.7
    0x7fc377cae000-0x7fc377caf000    /usr/lib64/libz.so.1.2.7
    0x7fc377caf000-0x7fc377cd8000    /usr/lib64/libpng15.so.15.13.0
    0x7fc377cd8000-0x7fc377ed8000    /usr/lib64/libpng15.so.15.13.0
    0x7fc377ed8000-0x7fc377ed9000    /usr/lib64/libpng15.so.15.13.0
    0x7fc377ed9000-0x7fc377eda000    /usr/lib64/libpng15.so.15.13.0
    0x7fc377eda000-0x7fc378106000    /home/test/Downloads/openjpeg-master-afl/openjpeg-master/build/bin/libopenjp2.so.2.2.0
    0x7fc378106000-0x7fc378306000    /home/test/Downloads/openjpeg-master-afl/openjpeg-master/build/bin/libopenjp2.so.2.2.0
    0x7fc378306000-0x7fc37830a000    /home/test/Downloads/openjpeg-master-afl/openjpeg-master/build/bin/libopenjp2.so.2.2.0
    0x7fc37830a000-0x7fc378315000    /home/test/Downloads/openjpeg-master-afl/openjpeg-master/build/bin/libopenjp2.so.2.2.0
    0x7fc378315000-0x7fc378335000    /usr/lib64/ld-2.17.so
    0x7fc3783a8000-0x7fc378519000   
    0x7fc378519000-0x7fc378534000   
    0x7fc378534000-0x7fc378535000    /usr/lib64/ld-2.17.so
    0x7fc378535000-0x7fc378536000    /usr/lib64/ld-2.17.so
    0x7fc378536000-0x7fc378537000   
    0x7fffc88bd000-0x7fffc88de000    [stack]
    0x7fffc8913000-0x7fffc8915000    [vdso]
    0xffffffffff600000-0xffffffffff601000    [vsyscall]
==65390==End of process memory map.
==65390==AddressSanitizer CHECK failed: /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:120 "((0 && "unable to mmap")) != (0)" (0x0, 0x0)
    #0 0x4ec0cf in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_rtl.cc:69
    #1 0x5039f5 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_termination.cc:79
    #2 0x4f4690 in __sanitizer::ReportMmapFailureAndDie(unsigned long, char const*, char const*, int, bool) /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common.cc:120
    #3 0x4fce6e in __sanitizer::MmapOrDie(unsigned long, char const*, bool) /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_posix.cc:132
    #4 0x42811f in __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback>::Allocate(__sanitizer::AllocatorStats*, unsigned long, unsigned long) /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_secondary.h:41
    #5 0x42811f in __sanitizer::CombinedAllocator<__sanitizer::SizeClassAllocator64<__asan::AP64>, __sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64> >, __sanitizer::LargeMmapAllocator<__asan::AsanMapUnmapCallback> >::Allocate(__sanitizer::SizeClassAllocatorLocalCache<__sanitizer::SizeClassAllocator64<__asan::AP64> >*, unsigned long, unsigned long, bool, bool) /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_allocator_combined.h:70
    #6 0x42811f in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:407
    #7 0x422c3d in __asan::asan_posix_memalign(void**, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*) /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:825
    #8 0x4e253d in __interceptor_posix_memalign /home/test/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:144
    #9 0x7fc3780eccb0 in opj_aligned_alloc_n /home/test/Downloads/openjpeg-master-afl/openjpeg-master/src/lib/openjp2/opj_malloc.c:61:9
    #10 0x7fc3780eccb0 in opj_aligned_malloc /home/test/Downloads/openjpeg-master-afl/openjpeg-master/src/lib/openjp2/opj_malloc.c:209
    #11 0x7fc377f31311 in opj_image_create /home/test/Downloads/openjpeg-master-afl/openjpeg-master/src/lib/openjp2/image.c:77:39
    #12 0x55cf48 in bmptoimage /home/test/Downloads/openjpeg-master-afl/openjpeg-master/src/bin/jp2/convertbmp.c:800:13
    #13 0x518cf5 in main /home/test/Downloads/openjpeg-master-afl/openjpeg-master/src/bin/jp2/opj_compress.c:1847:21
    #14 0x7fc3766ebb34 in __libc_start_main /usr/src/debug/glibc-2.17-c758a686/csu/../csu/libc-start.c:274
    #15 0x41cb0b in _start (/home/test/Downloads/openjpeg-master-afl/openjpeg-master/build/bin/opj_compress+0x41cb0b)

```
testcase:https://github.com/bestshow/p0cs/blob/master/allocation_failure_in_opj_aligned_alloc_n.bmp
Credit:ADLab of Venustech

**Comment by rouault** [comment]
This is in the same class of issue as #989
