### ISSUE TITLE
Integer-overflow (7651)

### ISSUE THREAD

**Issue by dlemstra** [uclouvain/openjpeg#1113]
The @ImageMagick project is using https://github.com/google/oss-fuzz to find bugs in our own library and in libraries that we use. The fuzzer found an issue and we think this is an issue that should be resolved in the library that we use. This issue is posted under the url https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=7651 that is not publicly visible yet but added as a link for future reference. Below are the details of the issue that can be reproduced using the following technique: https://github.com/google/oss-fuzz/blob/master/docs/reproducing.md

Stacktrace:
```
/src/openjpeg/src/lib/openjp2/t1.c:2173:55: runtime error: signed integer overflow: 34731935 * 64 cannot be represented in type 'int'
  | #0 0x9de33f in opj_t1_encode_cblks openjpeg/src/lib/openjp2/t1.c:2173:55
  | #1 0x9b3c2f in opj_tcd_t1_encode openjpeg/src/lib/openjp2/tcd.c:2511:11
  | #2 0x9b3c2f in opj_tcd_encode_tile openjpeg/src/lib/openjp2/tcd.c:1414
  | #3 0x98ef50 in opj_j2k_write_sod openjpeg/src/lib/openjp2/j2k.c:4685:11
  | #4 0x98ef50 in opj_j2k_write_first_tile_part openjpeg/src/lib/openjp2/j2k.c:11764
  | #5 0x98ef50 in opj_j2k_post_write_tile openjpeg/src/lib/openjp2/j2k.c:11521
  | #6 0x98eaf1 in opj_j2k_encode openjpeg/src/lib/openjp2/j2k.c:11270:15
  | #7 0x7b746f in WriteJP2Image imagemagick/coders/jp2.c:1083:29
  | #8 0x541312 in WriteImage imagemagick/MagickCore/constitute.c:1124:14
  | #9 0x50731e in ImageToBlob imagemagick/MagickCore/blob.c:1912:18
  | #10 0x49d72b in Magick::Image::write(Magick::Blob*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) imagemagick/Magick++/lib/Image.cpp:4896:8
  | #11 0x43012f in LLVMFuzzerTestOneInput imagemagick/Magick++/fuzz/encoder_fuzzer.cc:56:11
  | #12 0x43e6ec in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:517:13
  | #13 0x43076c in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
  | #14 0x4342e4 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:703:9
  | #15 0x430478 in main /src/libfuzzer/FuzzerMain.cpp:20:10
  | #16 0x7f0f3f28b82f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/libc-start.c:291
  | #17 0x408838 in _start
```

Links:
https://github.com/uclouvain/openjpeg/blob/2c7eb4fed9cbed43ae402840f6706998ce2dd1c4/src/lib/openjp2/t1.c#L2173
Commit: 2c7eb4fed9cbed43ae402840f6706998ce2dd1c4
Testcase file: [clusterfuzz-testcase-minimized-encoder_jpc_fuzzer-4642979265380352.zip](https://github.com/uclouvain/openjpeg/files/1908914/clusterfuzz-testcase-minimized-encoder_jpc_fuzzer-4642979265380352.zip)

**Comment by boxerab** [comment]
For the forward DWT transform of B-bit integers in range `-2^(B-1) <= x <= 2^(B-1)`,   `B+4)` bits are sufficient to represent these integers for reversible transform, without overflow. In the irreversible case,
we need one more bit.  (17.3 of Taubman and Marecellin).
Also, conversion to fixed point adds 6 "fraction" bits.
So, for precision P images, we need at most `(P + 5 + 6)` bits to avoid overflow.

Simplest solution is to enforce a limit of <= 16 bit precision for images input to encoder. I highly doubt anybody is compression > 16 bit images, but this limit should be explicitly enforced, and documented for user.
